# Generated by Django 3.2.5 on 2023-02-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
