# Generated by Django 3.2 on 2023-02-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0007_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_image',
            field=models.FileField(blank=True, null=True, upload_to='post_img'),
        ),
    ]
