# Generated by Django 3.2 on 2023-02-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0013_alter_friends_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaultImage.png', null=True, upload_to='profile_img'),
        ),
    ]
